### ISSUE TITLE
Is there a way to use Resources as SubResources?

### ISSUE THREAD

**Issue by Kronopt** [phalt/beckett#91]
I'm working on [pykemon](https://github.com/PokeAPI/pykemon), and many subresources are just other resources.

So I would like to avoid having to write almost exactly the same classes but as a subsesources

**Comment by phalt** [comment]
It should just work™ - give it a try and see.

**Comment by Kronopt** [comment]
Ok, I found out I can... but because there are some resources that have each other as subresources ( A is subresource of B and B is subresource of A) I can't define them both sequentially on the same file.
